// The only module that knows OpenRouter exists.
//
// Two things here are shaped by the free tier: the fallback chain, and the
// fact that mock mode is the default outside production. Fifty requests a day
// across the whole account is an hour of prompt debugging, so a live call has
// to be something you choose rather than something that happens.
import { env } from "../config/env.js";

const BASE_URL = "https://openrouter.ai/api/v1/chat/completions";

// Per attempt, not for the chain. Two of the three models below reason before
// answering, and on top of Render's cold start an unbounded wait means the
// user watches a spinner instead of getting the second model's answer.
const REQUEST_TIMEOUT_MS = 20_000;

/**
 * Longest body accepted, in characters.
 *
 * Measured rather than guessed. The good live insight was 219 characters, the
 * mock bodies run to about 200, and the seeded ones 124-132. The failure this
 * guards against — a full chain of thought — was 1293, and the real answer
 * buried inside it was around 340. 600 leaves comfortable room above anything
 * legitimate while rejecting a reasoning trace outright.
 */
const MAX_INSIGHT_LENGTH = 600;

/**
 * Tried in order. Three vendors on purpose, not three models from one.
 *
 * Free model ids are withdrawn without notice, and the failure worth guarding
 * against is the app breaking between submission and review. Two models from
 * the same vendor would be withdrawn in the same announcement and fall
 * together; these will not.
 */
export const MODEL_CHAIN = [
  "nvidia/nemotron-3-ultra-550b-a55b:free",
  "openai/gpt-oss-20b:free",
  "z-ai/glm-5.2:free",
] as const;

export interface ChatMessage {
  role: "system" | "user";
  content: string;
}

export interface CompletionResult {
  text: string;
  /** Which model answered, or "mock". Stored on the row and logged. */
  model: string;
}

export class InsightGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InsightGenerationError";
  }
}

/**
 * The first model in the chain that answers.
 *
 * Rejects only when all three have failed, which the service treats as a
 * signal to fall back to older stored content rather than as a request error.
 */
export async function generateCompletion(
  messages: ChatMessage[],
): Promise<CompletionResult> {
  if (env.mockLlm) {
    return { text: mockInsight(messages), model: "mock" };
  }

  const failures: string[] = [];

  for (const model of MODEL_CHAIN) {
    try {
      const text = await requestCompletion(model, messages);
      console.log(`Insight generated by ${model}.`);
      return { text, model };
    } catch (error) {
      // Expected often enough to be normal operation: a withdrawn model id is
      // a 404 here. Logged per model so the chain's behaviour is visible.
      const reason = error instanceof Error ? error.message : String(error);
      console.warn(`Insight model ${model} failed: ${reason}`);
      failures.push(`${model}: ${reason}`);
    }
  }

  throw new InsightGenerationError(
    `Every model in the chain failed. ${failures.join(" | ")}`,
  );
}

async function requestCompletion(
  model: string,
  messages: ChatMessage[],
): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let response: Response;
  try {
    response = await fetch(BASE_URL, {
      method: "POST",
      signal: controller.signal,
      headers: {
        Authorization: `Bearer ${env.openrouterApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        messages,
        // The output is two or three sentences; anything longer is a model
        // ignoring the brief, and paying for it in latency helps nobody.
        // Reasoning models spend tokens thinking before they answer, so this
        // is not as generous as it looks.
        max_tokens: 800,
        // Reasoning stays out of the response entirely. Documented at
        // openrouter.ai/docs/use-cases/reasoning-tokens: reasoning normally
        // returns in message.reasoning, and exclude keeps the model thinking
        // while dropping that from the reply. The row that caused this fix had
        // it folded into message.content instead, which is exactly what the
        // parse below is for — this parameter is the polite request, the parse
        // is the enforcement.
        reasoning: { exclude: true },
      }),
    });
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") {
      throw new Error(`no response within ${REQUEST_TIMEOUT_MS}ms`);
    }
    throw new Error(
      `request failed: ${error instanceof Error ? error.message : String(error)}`,
    );
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }

  let body: unknown;
  try {
    body = await response.json();
  } catch {
    throw new Error("response body was not JSON");
  }

  const content = extractContent(body);
  if (content === null) {
    throw new Error("response contained no message content");
  }

  // Throws on anything that is not the agreed shape, which the caller treats
  // as this model having failed.
  return parseInsightPayload(content);
}

// The provider's shape is checked rather than trusted, like any third party:
// an empty choices array or a null content field must become a fallback to the
// next model, not an empty insight stored for the day.
function extractContent(body: unknown): string | null {
  if (typeof body !== "object" || body === null) return null;

  const choices = (body as { choices?: unknown }).choices;
  if (!Array.isArray(choices) || choices.length === 0) return null;

  const message = (choices[0] as { message?: unknown }).message;
  if (typeof message !== "object" || message === null) return null;

  const content = (message as { content?: unknown }).content;
  if (typeof content !== "string" || content.trim() === "") return null;

  return content.trim();
}

/**
 * The message content, as the insight it is supposed to contain.
 *
 * Exported so the two checks below can be exercised without spending a call.
 *
 * This is the actual fix for reasoning traces reaching the reader, and it
 * works because it is a shape rather than a request. Asking the model not to
 * think out loud already failed: it read the rules and narrated its compliance
 * with them. A chain of thought is not valid JSON, so it cannot arrive quietly
 * mixed into the answer — the response either parses or it does not.
 *
 * Two independent checks, deliberately. The parse catches reasoning outside
 * the JSON; the ceiling catches a model that returns valid JSON with its
 * reasoning inside the string, which the parse alone would happily accept.
 */
export function parseInsightPayload(content: string): string {
  const json = stripCodeFence(content);

  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    // The failure mode this exists for. The reasoning trace that shipped was
    // well-formed prose, so nothing before this point could tell it apart
    // from an answer.
    throw new Error("content was not valid JSON");
  }

  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("content was JSON but not an object");
  }

  const insight = (parsed as { insight?: unknown }).insight;
  if (typeof insight !== "string") {
    throw new Error('JSON had no string "insight" field');
  }

  const trimmed = insight.trim();
  if (trimmed === "") {
    throw new Error('"insight" was empty');
  }

  if (trimmed.length > MAX_INSIGHT_LENGTH) {
    throw new Error(
      `insight was ${trimmed.length} characters, over the ${MAX_INSIGHT_LENGTH} limit`,
    );
  }

  return trimmed;
}

// Models asked for JSON often wrap it in a markdown fence regardless. That is
// formatting rather than a different answer, so it is unwrapped instead of
// being treated as a failure and costing another model in the chain.
function stripCodeFence(content: string): string {
  const fenced = /^```(?:json)?\s*\n([\s\S]*?)\n?```$/.exec(content.trim());
  return fenced ? fenced[1].trim() : content.trim();
}

/**
 * The canned insight used when MOCK_LLM is true. No network call.
 *
 * Deliberately unmistakable. It exists to exercise the plumbing end to end,
 * and the one thing it must never do is pass for a real answer in a
 * screenshot — hence the leading marker, which no model would produce.
 *
 * It still varies with the input, because a mock that reads the same for
 * every user would hide exactly the bug this section can have: serving one
 * person's insight to somebody else.
 */
function mockInsight(messages: ChatMessage[]): string {
  const userMessage = messages.find((message) => message.role === "user");
  const lines = userMessage?.content.split("\n") ?? [];

  const investorType =
    lines.find((line) => line.startsWith("Investor type:"))?.slice(15).trim() ??
    "investor";

  // Reads the symbols back out of the price lines, so the mock names the
  // assets this user actually holds.
  const symbols = lines
    .filter((line) => line.startsWith("- ") && line.includes("("))
    .map((line) => line.slice(line.indexOf("(") + 1, line.indexOf(")")))
    .filter((symbol) => symbol.length > 0);

  const holdings = symbols.length > 0 ? symbols.join(", ") : "your assets";

  return (
    `[MOCK INSIGHT — no language model was called] ` +
    `Today's numbers for ${holdings} are on screen above, and as a ${investorType} ` +
    `you are the audience this note is written for. ` +
    `Set MOCK_LLM=false to generate a real one.`
  );
}
