// The only module that knows OpenRouter exists.
//
// Two things here are shaped by the free tier: the fallback chain, and the
// fact that mock mode is the default outside production. Fifty requests a day
// across the whole account is an hour of prompt debugging, so a live call has
// to be something you choose rather than something that happens.
import { env } from "../config/env.js";

const BASE_URL = "https://openrouter.ai/api/v1/chat/completions";

// Per attempt, not for the chain. Two of the three models below reason before
// answering, and on top of Render's cold start an unbounded wait means the
// user watches a spinner instead of getting the second model's answer.
const REQUEST_TIMEOUT_MS = 20_000;

/**
 * Tried in order. Three vendors on purpose, not three models from one.
 *
 * Free model ids are withdrawn without notice, and the failure worth guarding
 * against is the app breaking between submission and review. Two models from
 * the same vendor would be withdrawn in the same announcement and fall
 * together; these will not.
 */
export const MODEL_CHAIN = [
  "nvidia/nemotron-3-ultra-550b-a55b:free",
  "openai/gpt-oss-20b:free",
  "z-ai/glm-5.2:free",
] as const;

export interface ChatMessage {
  role: "system" | "user";
  content: string;
}

export interface CompletionResult {
  text: string;
  /** Which model answered, or "mock". Stored on the row and logged. */
  model: string;
}

export class InsightGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InsightGenerationError";
  }
}

/**
 * The first model in the chain that answers.
 *
 * Rejects only when all three have failed, which the service treats as a
 * signal to fall back to older stored content rather than as a request error.
 */
export async function generateCompletion(
  messages: ChatMessage[],
): Promise<CompletionResult> {
  if (env.mockLlm) {
    return { text: mockInsight(messages), model: "mock" };
  }

  const failures: string[] = [];

  for (const model of MODEL_CHAIN) {
    try {
      const text = await requestCompletion(model, messages);
      console.log(`Insight generated by ${model}.`);
      return { text, model };
    } catch (error) {
      // Expected often enough to be normal operation: a withdrawn model id is
      // a 404 here. Logged per model so the chain's behaviour is visible.
      const reason = error instanceof Error ? error.message : String(error);
      console.warn(`Insight model ${model} failed: ${reason}`);
      failures.push(`${model}: ${reason}`);
    }
  }

  throw new InsightGenerationError(
    `Every model in the chain failed. ${failures.join(" | ")}`,
  );
}

async function requestCompletion(
  model: string,
  messages: ChatMessage[],
): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  let response: Response;
  try {
    response = await fetch(BASE_URL, {
      method: "POST",
      signal: controller.signal,
      headers: {
        Authorization: `Bearer ${env.openrouterApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        messages,
        // The output is two or three sentences; anything longer is a model
        // ignoring the brief, and paying for it in latency helps nobody.
        max_tokens: 300,
      }),
    });
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") {
      throw new Error(`no response within ${REQUEST_TIMEOUT_MS}ms`);
    }
    throw new Error(
      `request failed: ${error instanceof Error ? error.message : String(error)}`,
    );
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }

  let body: unknown;
  try {
    body = await response.json();
  } catch {
    throw new Error("response body was not JSON");
  }

  const text = extractText(body);
  if (text === null) {
    throw new Error("response contained no message content");
  }
  return text;
}

// The provider's shape is checked rather than trusted, like any third party:
// an empty choices array or a null content field must become a fallback to the
// next model, not an empty insight stored for the day.
function extractText(body: unknown): string | null {
  if (typeof body !== "object" || body === null) return null;

  const choices = (body as { choices?: unknown }).choices;
  if (!Array.isArray(choices) || choices.length === 0) return null;

  const message = (choices[0] as { message?: unknown }).message;
  if (typeof message !== "object" || message === null) return null;

  const content = (message as { content?: unknown }).content;
  if (typeof content !== "string" || content.trim() === "") return null;

  return content.trim();
}

/**
 * The canned insight used when MOCK_LLM is true. No network call.
 *
 * Deliberately unmistakable. It exists to exercise the plumbing end to end,
 * and the one thing it must never do is pass for a real answer in a
 * screenshot — hence the leading marker, which no model would produce.
 *
 * It still varies with the input, because a mock that reads the same for
 * every user would hide exactly the bug this section can have: serving one
 * person's insight to somebody else.
 */
function mockInsight(messages: ChatMessage[]): string {
  const userMessage = messages.find((message) => message.role === "user");
  const lines = userMessage?.content.split("\n") ?? [];

  const investorType =
    lines.find((line) => line.startsWith("Investor type:"))?.slice(15).trim() ??
    "investor";

  // Reads the symbols back out of the price lines, so the mock names the
  // assets this user actually holds.
  const symbols = lines
    .filter((line) => line.startsWith("- ") && line.includes("("))
    .map((line) => line.slice(line.indexOf("(") + 1, line.indexOf(")")))
    .filter((symbol) => symbol.length > 0);

  const holdings = symbols.length > 0 ? symbols.join(", ") : "your assets";

  return (
    `[MOCK INSIGHT — no language model was called] ` +
    `Today's numbers for ${holdings} are on screen above, and as a ${investorType} ` +
    `you are the audience this note is written for. ` +
    `Set MOCK_LLM=false to generate a real one.`
  );
}
